### ISSUE TITLE
UMD style require is ignored (necessary for `jsonc-parser`)

### ISSUE THREAD

**Issue by styfle** [zeit/node-file-trace#107]
## Steps to reproduce

```sh
mkdir umd
cd umd
yarn init -y
yarn add jsonc-parser@2.2.1
echo "const { parse } = require('jsonc-parser')" > index.js
nft print index.js
```

Notice that [lib/umd/main.js](https://unpkg.com/browse/jsonc-parser@2.2.1/lib/umd/main.js) is found but nothing from [lib/umd/impl](https://unpkg.com/browse/jsonc-parser@2.2.1/lib/umd/impl/).

cc @WesSouza

**Comment by styfle** [comment]
@guybedford This is not intentional, correct?

**Comment by guybedford** [comment]
Yes - UMD patterns obscure the `require` binding through the IIFE so the analysis doesn't see it as a require. We handle this by having fixed UMD pattern detections in https://github.com/zeit/node-file-trace/blob/master/src/utils/wrappers.js that are able to effectively "unwrap" these UMD wrappers to "see" the require since the analysis on its own can't quite do that.

Handling this pattern could be done by implementing a wrapper implementation for it as per those patterns.
