### ISSUE TITLE
fs.readdir(Sync) doesn't preserve directory

### ISSUE THREAD

**Issue by jkrems** [zeit/node-file-trace#78]
I would have expected that the following code preserves the directory in question:

```js
fs.readdir('/some/dir', () => { /* actual code */ });
```

But it doesn't. The following does:

```js
fs.stat('/some/dir', () => { /* ignored, just here for the tracer */ });
fs.readdir('/some/dir', () => { /* actual code */ });
```

Was this a conscious design decision?

**Comment by styfle** [comment]
Looks like a bug to me, thanks!

**Comment by jkrems** [comment]
Thanks for confirming! Also, sorry for the issue flood. Wanted to document these things while my memory was still fresh. :)

**Comment by styfle** [comment]
@jkrems The "flood" is perfect because it narrows down the bugs to the smallest repro steps. Thanks!

**Comment by guybedford** [comment]
This is not so much about the directory being ignored or not, and more just that the way asset references are detected is based on anytime you have a handle to a full file path to something, it is deemed a reference. For an example analog, an `import.meta.url` that escapes analysis is deemed a "free asset reference" which should be included / inlined to its source expression.

More advanced analysis would ideally handle the concept of a "sink". Eg `console.log(import.meta.url)` has no need to emit an asset because the `console.log` statement can be regarded as an analysis sink in that no file functions get hold of the reference.

In this same way it seems like you are expecting `fs.readdir` to act as an analysis sink for the asset reference, but we don't have full tracing of analysis source to sink in the current approach unfortunately for this to work.

@jkrems do you have an explicit test case / full scenario where this is in usage for us to consider how to treat this / resolve the underlying issue?

**Comment by jkrems** [comment]
The actual code I was using is here: https://github.com/azukaru/progressive-fetching/pull/5/files#diff-d9c6ec01349c957e389e5769c466223aR20. The pseudo-code summary is:

```js
const chunkDir = path.resolve('.next', 'static', 'chunks');
const lookupIndex = buildLookup(fs.readdirSync(chunkDir));
return id => {
  return fs.readFileSync(getFilenameFromId(id));
};
```

Right now `readdirSync` doesn't count as an asset reference as well. So the above code isn't enough to preserve `chunkDir`. I think if a `stat` of a directory is treated as a glob-style asset reference, `readdir` should as well. Unless there's patterns I'm not aware of where `readdir` could lead to overly broad inclusions.

**Comment by guybedford** [comment]
@jkrems so the thing is, that:

```js
const chunkDir = path.resolve('.next', 'static', 'chunks');
```

is actually all that is needed to create an asset emission.

The reason for this is that asset analysis cannot be expected to analyze every possible code path (especially given the ability for references to escape any level of analysis).

As a result the only full-proof way to detect references to assets is to detect the source expressions (and as a side note, this is why I put such importance on `import.meta.url` and `import.meta.resolve` in ES module analysis as they are the _only_ source of local references, apart from `process.cwd()` and functions that use the `process.cwd()` capability).

If we dig into the exact case again, I expect that we will find that `chunkDir` exactly is being analyzed and emitted by this project, but rather failing the filter. It should be possible to detect this by enabling the `log: true` feature, and looking for a message like https://github.com/zeit/node-file-trace/blob/master/src/analyze.js#L746. Alternatively the filter paths can be debugged manually.

**Comment by guybedford** [comment]
In terms of filter fixes - yes treating a `fs.readdirSync` expression as something that explicitly turns off filtering, or having some more fine-grained behaviours in place could be a way to achieve this.

**Comment by jkrems** [comment]
I'm fairly certain I tracked it down to `readdirSync` not being in this list: https://github.com/zeit/node-file-trace/blob/3b59df9b1d594c375f8549d5a6d3e5df2e03fb33/src/analyze.js#L42-L57. `path.join` wasn't enough, it's just statically evaluated using the native implementation: https://github.com/zeit/node-file-trace/blob/3b59df9b1d594c375f8549d5a6d3e5df2e03fb33/src/analyze.js#L124-L136

**Comment by guybedford** [comment]
`path.resolve` is specifically analyzed with the local `process.cwd()` for the project - https://github.com/zeit/node-file-trace/blob/3b59df9b1d594c375f8549d5a6d3e5df2e03fb33/src/analyze.js#L139.

Perhaps the analysis cwd wasn't matching the project cwd, which would result in no emission?

`fs.readdir` is entirely redundant here - the emission is about the emission expression. Fs triggers as with `FS_FN` are for generating emission sources where there might not otherwise have been. For example `fs.readFile('asdf')` being cwd-relative, where we don't want to analyze every `'asdf'` string.

**Comment by jkrems** [comment]
Can't repro in simple unit test against latest master. So this doesn't seem to be an issue anymore. I'm pretty sure it used to go away when adding `stat`, independent of any calls to `resolve`. But looks like I can't reproduce that. :)
